### ISSUE TITLE
Ability to copy path to node

### ISSUE THREAD

**Issue by nils-jansen** [AykutSarac/jsoncrack.com#198]
### Feature

When clicking on a node, display the option to copy the path to that node to the clipboard.
Possibly next to the "Clipboard" button:
![image](https://user-images.githubusercontent.com/20142304/191909124-4252fdf2-6546-4589-bbc9-0abb785122d0.png)

**Comment by eLeontev** [comment]
hey, I can take care, could you clarify/confirm criteria?

My suggestion:
1. add UI button (the same color as in clipboard + no icon)
2. click to the button will will replace all clipboard data to path to the displayed node as a string with format TODO)

Alternative:
we can display path to the node in the node modal header with clipboard button there

**Comment by AykutSarac** [comment]
What exactly is meant by path here?

**Comment by nils-jansen** [comment]
Example:
```json
{ "one": { "two": { "three": 4 } } }
```

The path for "4" would be `one.two.three`.

**Comment by eLeontev** [comment]
> Example:
> 
> ```json
> { "one": { "two": { "three": 4 } } }
> ```
> 
> The path for "4" would be `one.two.three`.

I faced the limitation for expected result: 
- in the editor we have term "node" - it's represented as a independent block of data. In your example we don't have node `4` but we have node `{three: 4}`
- 
![image](https://user-images.githubusercontent.com/15786916/199719617-04ecd150-5c38-46fc-b29f-c124c7c23dba.png)

so the expected result will be `one.two` instead of `one.two.three`

not sure if it's achievable at all since all editor designed for this type of data representation. @AykutSarac please confirm

btw workaround to achieve the result is: `{ "one": { "two": { "three": [4] } } }` in this case `4` will be represented as a node and path to it will be `one.two.three`

p.s. current api cannot handle element position by it's index, so in example `{"prop": [1, 2, 3]}` path for each element of array is `prop`

**Comment by AykutSarac** [comment]
I think we can wait for #251 to be merged first, it changes whole parsing algorithm.
