### ISSUE TITLE
[BUG]: search not updating upon content change

### ISSUE THREAD

**Issue by fxzer** [AykutSarac/jsoncrack.com#308]
## Operation demonstration

https://user-images.githubusercontent.com/68853957/215651694-ca012eed-8bbe-4e7c-85b3-5f957a69e88f.gif

1. search with 'members'
2. Change 'members' to 'memers'
3. The search box searches for ‘members’，But the focus is still in its original position！

![2023-01-31 10 56 45](https://user-images.githubusercontent.com/68853957/215652310-f6737b7b-5ac5-41ab-bfa0-f51d511f760c.gif)

### Operating system

- OS: MacOS 13:
- Browser : chrome 

- Any other details...

### Priority this issue should have

Low (slightly annoying)

**Comment by Nikblaze** [comment]
The issue is in useFocusNode.tsx file where useeffect is called which calls file search.tsx which adds or removes highlight class. But there is no relation for the json data provided in the editor, that's why on changing json Data from editor doesn't affect the highlight class.
We can get the json data and use it in useeffect() as trigger in useFocusNode.tsx file which is solving the issue.

But there is one concern that since search of node is based on parameter 
``span[data-key*='${content.debounced}' i]``
which is not updated as soon as json data is changed from editor, so adding 100ms timeout in useeffect solves the issue as in this time span gets the class and search.tsx is able to identify the node.

It would be great if I can take this issue.

**Comment by Nikblaze** [comment]
https://github.com/AykutSarac/jsoncrack.com/pull/312

This is PR for the proposed solution.
@AykutSarac

**Comment by Shahidullah-Muffakir** [comment]
Can I work on this Issue?
It seems it still pending

**Comment by Shahidullah-Muffakir** [comment]
Can I work on this issue?
It seems it is still pending

**Comment by AykutSarac** [comment]
> Can I work on this issue? It seems it is still pending

Sure
