### ISSUE TITLE
Upgrade to premium for free

### ISSUE THREAD

**Issue by abhishekj44** [AykutSarac/jsoncrack.com#374]
### Feature

I have a json that has more then thousand attributes and to convert those into graph it asks to upgrade to premium version and since it is open source is there a way to get it for free?

**Comment by AykutSarac** [comment]
While you can modify it from [this source](https://github.com/AykutSarac/jsoncrack.com/blob/main/src/store/useUser.ts#L24), it's important to recognize that the project is open-source to foster community collaboration and share knowledge. Please, acknowledge the efforts and time invested in the development of this project and consider supporting it instead of bypassing premium features. :)
